### ISSUE TITLE
memory overflow

### ISSUE THREAD

**Issue by vick2075** [artmenlope/double-slit-2d-schrodinger#1]
Hi,

I have two issues:
1) double slit FPB CN has "doubleSlit_interaction" function that is not referenced beforehand.
2) I am having troubles running the other file....I'm using Python 3.9 on Windows 10 8GB Ram and CPU 2.7 GHz on a 64 bit processor.

**Comment by JoaoCLFolhadela** [comment]
Think you just have to reduce the parameters, like time used, box size... it will make the simulation worse but at least you will have one

**Comment by artmenlope** [comment]
First of all, sorry for the very late response.

Regarding the first issue, it is a mistake for the `doubleSlit_interaction` function to be there in line 125. That line should be completely removed.

To answer the second point, as I say in the README.md file, the method used is known to be more stable at the cost of being computationally expensive. In my case, having similar specs to your computer (mine has CPU 2.50 GHz), the running time of the program was of the order of an hour if I can remember well. The scripts could be optimized but, as @Ragdraco said, maybe playing with the parameters of the simulation could help you.

**Comment by vick2075** [comment]
Thank you all of you.
